
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # Удаляет пробелы в конце строк
      - id: end-of-file-fixer    # Добавляет пустую строку в конце файла
      - id: check-yaml           # Проверяет синтаксис YAML файлов

#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.14.6
#    hooks:
#      - id: ruff-check
#        args: [--fix]
#      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
